language: haskell

ghc: 8.2.2

script:
    - travis_wait 30 cabal configure --enable-benchmarks && cabal build && cabal bench compare

install:
    - cabal install --only-dependencies --enable-benchmarks
