language: haskell

ghc: 8.2.2

env:
    - DO=TIME STEP=0
    - DO=TIME STEP=1
    - DO=TIME STEP=2
    - DO=TIME STEP=3
    - DO=SPACE
    - DO=DATASIZE

cache:
    directories:
        - $HOME/.cabal/packages
        - $HOME/.cabal/store
        - $HOME/.cabal/bin

script:
    - cabal configure --enable-benchmarks 
    - cabal build
    - if [ $DO = DATASIZE ]; then ./dist/build/datasize/datasize; else if [ $DO = SPACE ]; then ./dist/build/space/space; else ./dist/build/time/time run --part $STEP --of 4 --graphs-size "(3,3,2)"; fi; fi;

install:
    - git clone https://github.com/patrickdoc/hash-graph.git /tmp/hash-graph
    - cabal install /tmp/hash-graph
    - cabal install --only-dependencies --enable-benchmarks
