language: haskell

ghc: 8.2.2

script:
    - cabal configure --enable-benchmarks 
    - cabal build 
    - travis_wait 30 cabal bench compare

install:
    - cabal install --only-dependencies --enable-benchmarks
