language: haskell

ghc: 8.2.2

script:
    - cabal configure --enable-benchmarks 
    - cabal build
    - travis_wait 45 cabal bench compare

install:
    - git clone https://github.com/patrickdoc/hash-graph.git /tmp/hash-graph
    - cabal install /tmp/hash-graph
    - cabal install --only-dependencies --enable-benchmarks
