language: haskell

ghc: 8.2.2

script:
    - cabal configure --enable-benchmarks 
    - cabal build
    - IFS=$'\n'; for bench in $(./dist/build/compare/compare --list); do ./dist/build/compare/compare "$bench"; done;  

install:
    - git clone https://github.com/patrickdoc/hash-graph.git /tmp/hash-graph
    - cabal install /tmp/hash-graph
    - cabal install --only-dependencies --enable-benchmarks
