resolver: lts-11.15

packages:
  - '.'

extra-deps:
  - git: https://github.com/patrickdoc/hash-graph.git
    commit: 785c20dc608774b133d89c942bc33d7f56ef6ced
  - git: https://github.com/snowleopard/alga.git
    commit: 91eb3b4b535259508ef196d16429c2899da9949e
  - ghc-datasize-0.2.0
  - ghc-heap-view-0.5.10
  - criterion-1.4.0.0
  - base-compat-batteries-0.10.1
  - Chart-cairo-1.9
  - Chart-1.9

flags:
  ghc-heap-view:
    ghc_8_0: false
    ghc_8_2: true
