resolver: lts-11.15

packages:
  - '.'

extra-deps:
  - git: https://github.com/patrickdoc/hash-graph.git
    commit: 785c20dc608774b133d89c942bc33d7f56ef6ced
  - git: https://github.com/snowleopard/alga.git
    commit: 64e4d908c15d5e79138c6445684b9bef27987e8c
  - ghc-datasize-0.2.0
  - ghc-heap-view-0.5.10
  - criterion-1.4.0.0
  - base-compat-batteries-0.10.1

flags:
  ghc-heap-view:
    ghc_8_0: false
    ghc_8_2: true
