resolver: lts-11.15

packages:
  - '.'

extra-deps:
  - git: https://github.com/patrickdoc/hash-graph.git
    commit: 785c20dc608774b133d89c942bc33d7f56ef6ced
  - git: https://github.com/snowleopard/alga.git
    commit: 7c585142afc3811dc44093f5e6e7165f6f609539
  - git: https://github.com/travitch/haggle.git
    commit: 3bd2d560fbd1a2b60d49b3019d769f44da80c5d7 
  - ghc-datasize-0.2.0
  - ghc-heap-view-0.5.10
  - criterion-1.4.0.0
  - base-compat-batteries-0.10.1
  - monad-primitive-0.1
  - ref-tf-0.4.0.1

flags:
  ghc-heap-view:
    ghc_8_0: false
    ghc_8_2: true
